---
- name: Build server config
  hosts: web
  become: yes

  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
         path: /home/dockerfile/
         name: ansible
         tag: v1
