---
# tasks file for webserver]
- name: Ensure packages is present
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - tomcat8
    - rsync




- name: Synchronization using rsync protocol (pull)
  synchronize:
    mode: pull
    src: rsync://52.188.123.237/tmp/boxfuse-sample-java-war-hello/target/hello-1.0
    dest: /var/lib//tomcat8/webapps/hello-1.0/
    dest_port: 22
  delegate_to: 52.247.109.255 #Адрес сервера web

#- name: Copy file
#  command: rsync -avz root@52.188.123.237:/tmp/boxfuse-sample-java-war-hello/target/hello-1.0/ /var/lib/tomcat8/webapps/hello-1.0/

  notify:
    - restart tomcat
